/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package integrador_300;

import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author raul.nava
 */
public class frmCostos extends javax.swing.JFrame {

    /**
     * Creates new form frmCostos
     */
    //VARIABLES INVERSION INICIAL
    public static double varAcumuladorA = 0;
    public static double varAcumuladorB = 0;
    public static double varAcumuladorC = 0;
    public static double varAcumuladorD = 0;
    public static double varAcumuladorE = 0;
    public static double varAcumuladorF = 0;
    public static double varAcumuladorG = 0;
    public static double varTotalInversion = 0;
    
    //VARIABLES DE BALANCE INICIAL
    public static double varAcumuladorActivoCorriente = 0;
    public static double varAcumuladorActivoFijo = 0;
    public static double varAcumuladorActivoDiferido = 0;
    public static double varTotalActivo = 0;
    public static double varAcumuladorPasivoCirculante = 0;
    public static double varAcumuladorCapital = 0;
    public static double varPasivoMasCapital = 0;
    
    //VARIABLES DE MATERIA PRIMA
    public static double varAcumuladorMPrimaDirecta = 0;
    public static double varAcumuladorMPrimaIndirecta = 0;

    public frmCostos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTable14 = new javax.swing.JTable();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTable15 = new javax.swing.JTable();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTable16 = new javax.swing.JTable();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(243, 222, 243));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("PROYECTO INTEGRADOR TERCER SEMESTRE");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("MAQUINARIA Y EQUIPO");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Concepto", "Cantidad", "Precio unitario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane12.setViewportView(jTable1);

        jLabel3.setText("SUBTOTAL:");

        jLabel4.setText("$");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("$");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("VEHÍCULOS");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Concepto", "Cantidad", "Precio unitario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
        });
        jScrollPane13.setViewportView(jTable2);

        jLabel7.setText("SUBTOTAL:");

        jLabel8.setText("$");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setText("$");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("EQUIPO DE CÓMPUTO");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Concepto", "Cantidad", "Precio unitario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable3MouseEntered(evt);
            }
        });
        jScrollPane14.setViewportView(jTable3);

        jLabel11.setText("SUBTOTAL:");

        jLabel12.setText("$");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel13.setText("$");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("EQUIPO DE OFICINA");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Concepto", "Cantidad", "Precio unitario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable4MouseEntered(evt);
            }
        });
        jScrollPane15.setViewportView(jTable4);

        jLabel15.setText("SUBTOTAL:");

        jLabel16.setText("$");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel17.setText("$");

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel18.setText("CONSTRUCCIONES");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Concepto", "Cantidad", "Precio unitario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable5MouseEntered(evt);
            }
        });
        jScrollPane16.setViewportView(jTable5);

        jLabel19.setText("SUBTOTAL:");

        jLabel20.setText("$");

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel21.setText("$");

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel22.setText("CAPITAL DE TRABAJO");

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Concepto", "Cantidad", "Precio unitario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable6MouseEntered(evt);
            }
        });
        jScrollPane17.setViewportView(jTable6);

        jLabel23.setText("SUBTOTAL:");

        jLabel24.setText("$");

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel25.setText("$");

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel26.setText("DIFERIDOS");

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Concepto", "Cantidad", "Precio unitario", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable7MouseEntered(evt);
            }
        });
        jScrollPane18.setViewportView(jTable7);

        jLabel27.setText("SUBTOTAL:");

        jLabel28.setText("$");

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel29.setText("$");

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel30.setText("TOTAL DE INVERSIÓN:");

        jLabel31.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel31.setText("$");

        jLabel32.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel32.setText("ORIGEN INICIAL DE LOS RECURSOS");

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Concepto", "Cantidad", "Porcentaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable8MouseEntered(evt);
            }
        });
        jScrollPane19.setViewportView(jTable8);

        jLabel33.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel33.setText("CONTRIBUCIÓN DE LOS SOCIOS");

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Concepto", "% Contribución", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable9MouseEntered(evt);
            }
        });
        jScrollPane20.setViewportView(jTable9);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel15)
                                .addGap(178, 178, 178)
                                .addComponent(jLabel16)
                                .addGap(90, 90, 90)
                                .addComponent(jLabel17))
                            .addComponent(jLabel18)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(127, 127, 127)
                                        .addComponent(jLabel11)
                                        .addGap(167, 167, 167)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(jLabel27)
                                        .addGap(155, 155, 155)
                                        .addComponent(jLabel28))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(jLabel23)
                                        .addGap(160, 160, 160)
                                        .addComponent(jLabel24))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(jLabel19)
                                        .addGap(162, 162, 162)
                                        .addComponent(jLabel20)))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel31)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(156, 156, 156)
                                        .addComponent(jLabel4)
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel9)))
                                .addGap(179, 179, 179)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(97, 97, 97))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel30)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(36, 36, 36))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(37, 37, 37)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))))
                .addContainerGap(494, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jTabbedPane1.addTab("Inversión inicial", jScrollPane1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel34.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel34.setText("NOMBRE DE LA EMPRESA: TESSFP");

        jLabel35.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jLabel35.setText("PERIODO: ENERO A DICIEMBRE DE 2023");

        jLabel36.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel36.setText("ACTIVO CORRIENTE");

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Recurso", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable10MouseEntered(evt);
            }
        });
        jScrollPane21.setViewportView(jTable10);

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("TOTAL DE ACTIVO CIRCULANTE:");
        jLabel37.setOpaque(true);

        jLabel38.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel38.setText("$");

        jLabel39.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel39.setText("ACTIVO NO CORRIENTE");

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Recurso", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable11MouseEntered(evt);
            }
        });
        jScrollPane22.setViewportView(jTable11);

        jLabel40.setText("TOTAL DE ACTIVO FIJO:");

        jLabel41.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel41.setText("$");

        jLabel42.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel42.setText("ACTIVO DIFERIDO");

        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Recurso", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable12MouseEntered(evt);
            }
        });
        jScrollPane23.setViewportView(jTable12);

        jLabel43.setText("TOTAL ACTIVO DIFERIDO:");

        jLabel44.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel44.setText("$");

        jLabel45.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel45.setText("TOTAL DE ACTIVO:");

        jLabel46.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel46.setText("$");

        jLabel47.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel47.setText("PASIVO CIRCULANTE");

        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Recurso", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable13MouseEntered(evt);
            }
        });
        jScrollPane24.setViewportView(jTable13);

        jLabel48.setText("TOTAL PASIVO CIRCULANTE:");

        jLabel49.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel49.setText("$");

        jLabel50.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel50.setText("CAPITAL");

        jTable14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Recurso", "Capital"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable14MouseEntered(evt);
            }
        });
        jScrollPane25.setViewportView(jTable14);

        jLabel51.setText("TOTAL DE CAPITAL:");

        jLabel52.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel52.setText("$");

        jLabel53.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel53.setText("SUMA DE PASIVO + CAPITAL:");

        jLabel54.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel54.setText("$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(323, 323, 323))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(83, 83, 83)
                                    .addComponent(jLabel37)
                                    .addGap(176, 176, 176)
                                    .addComponent(jLabel38))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addGap(220, 220, 220))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel39)
                                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addComponent(jLabel47))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(184, 184, 184))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(161, 161, 161)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel50)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel48)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel49))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(172, 172, 172)
                                        .addComponent(jLabel51)
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel52))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(148, 148, 148)
                                        .addComponent(jLabel53)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel54)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel43)
                                .addGap(195, 195, 195)
                                .addComponent(jLabel44))
                            .addComponent(jLabel42)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel45)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel46)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel37))))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54))
                .addGap(35, 35, 35)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46))
                .addContainerGap(1614, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        jTabbedPane1.addTab("Balance inicial", jScrollPane2);

        jTable15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Insumos", "Unidad", "Cantidad por mes", "Costo unitario", "Costo total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable15MouseEntered(evt);
            }
        });
        jScrollPane26.setViewportView(jTable15);

        jTable16.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Insumos", "Unidad", "Cantidad por mes", "Costo unitario", "Costo total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable16MouseEntered(evt);
            }
        });
        jScrollPane27.setViewportView(jTable16);

        jLabel55.setText("Materia prima directa");

        jLabel56.setText("Materia prima indirecta");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel56)
                    .addComponent(jLabel55)
                    .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                    .addComponent(jScrollPane27))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel55)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel56)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1553, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel4);

        jTabbedPane1.addTab("Materia prima", jScrollPane3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2065, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(jPanel5);

        jTabbedPane1.addTab("Mano de obra", jScrollPane4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2065, Short.MAX_VALUE)
        );

        jScrollPane5.setViewportView(jPanel6);

        jTabbedPane1.addTab("CIF", jScrollPane5);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2065, Short.MAX_VALUE)
        );

        jScrollPane6.setViewportView(jPanel7);

        jTabbedPane1.addTab("Gastos de venta", jScrollPane6);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2065, Short.MAX_VALUE)
        );

        jScrollPane7.setViewportView(jPanel8);

        jTabbedPane1.addTab("Gastos financieros", jScrollPane7);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2065, Short.MAX_VALUE)
        );

        jScrollPane8.setViewportView(jPanel9);

        jTabbedPane1.addTab("Determinación de costos", jScrollPane8);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2065, Short.MAX_VALUE)
        );

        jScrollPane9.setViewportView(jPanel10);

        jTabbedPane1.addTab("Punto de equilibrio", jScrollPane9);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2065, Short.MAX_VALUE)
        );

        jScrollPane10.setViewportView(jPanel11);

        jTabbedPane1.addTab("Proyección de ventas", jScrollPane10);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2065, Short.MAX_VALUE)
        );

        jScrollPane11.setViewportView(jPanel12);

        jTabbedPane1.addTab("ROI", jScrollPane11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TABLAS DE INVERSIÓN INICIAL
        DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel modelo3 = (DefaultTableModel) jTable3.getModel();
        DefaultTableModel modelo4 = (DefaultTableModel) jTable4.getModel();
        DefaultTableModel modelo5 = (DefaultTableModel) jTable5.getModel();
        DefaultTableModel modelo6 = (DefaultTableModel) jTable6.getModel();
        DefaultTableModel modelo7 = (DefaultTableModel) jTable7.getModel();
        DefaultTableModel modelo8 = (DefaultTableModel) jTable8.getModel();
        DefaultTableModel modelo9 = (DefaultTableModel) jTable9.getModel();
        DefaultTableModel modelo10 = (DefaultTableModel) jTable10.getModel();      
        
        //Llenar la tabla 1 a 5
        for (int i = 0; i < 8; i++){
            modelo1.setValueAt("-", i, 0);
            modelo2.setValueAt("-", i, 0);
            modelo3.setValueAt("-", i, 0);
            modelo4.setValueAt("-", i, 0);
            modelo5.setValueAt("-", i, 0);
            for (int j = 1; j < 4; j++){
                modelo1.setValueAt("0", i, j);
                modelo2.setValueAt("0", i, j);
                modelo3.setValueAt("0", i, j);
                modelo4.setValueAt("0", i, j);
                modelo5.setValueAt("0", i, j);
            }
        }
        
        //Llenar la tabla 6 a 7
        for (int i = 0; i < 3; i++){
            modelo6.setValueAt("-", i, 0);
            modelo7.setValueAt("-", i, 0);
            for (int j = 1; j < 4; j++){
                modelo6.setValueAt("0", i, j);
                modelo7.setValueAt("0", i, j);
           }
        }
        
        //Llenar la tabla 8
        modelo8.setValueAt("FINANCIAMIENTO EXTERNO", 0, 0);
        modelo8.setValueAt("CONTRIBUCIÓN DE SOCIOS", 1, 0);
        modelo8.setValueAt("TOTAL", 2, 0);
        for (int i = 0; i < 3; i++){
            for (int j = 1; j < 3; j++){
                modelo8.setValueAt("0", i, j);
           }
        }
        
        //Llenar la tabla 9
        modelo9.setValueAt("SOCIO 01", 0, 0);
        modelo9.setValueAt("SOCIO 02", 1, 0);
        modelo9.setValueAt("SOCIO 03", 2, 0);
        modelo9.setValueAt("TOTAL DE SOCIOS", 3, 0);
        for (int i = 0; i < 4; i++){
            for (int j = 1; j < 3; j++){
                modelo9.setValueAt("0", i, j);
           }
        }
        
        //TABLAS DEL BALANCE INICIAL
        modelo10.setValueAt("CAJA", 0, 0);
        modelo10.setValueAt("0", 0, 1);
        modelo10.setValueAt("INVENTARIOS", 1, 0);
        modelo10.setValueAt("0", 1, 1);
        
        //TABLAS DE MATERIA PRIMA
        DefaultTableModel modelo15 = (DefaultTableModel) jTable15.getModel();
        DefaultTableModel modelo16 = (DefaultTableModel) jTable16.getModel();   
        for (int i = 0; i < 7; i++){
            modelo15.setValueAt("-", i, 0);
            modelo16.setValueAt("-", i, 0);
            for (int j = 1; j < 4; j++){
                modelo15.setValueAt("0", i, j);
                modelo16.setValueAt("0", i, j);
           }
        }


               
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TABLA 01
        DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();
        int varCantidadA = 0;
        double varPrecioA = 0, varTotalA = 0;
        String varCadena1, varCadena2;
        
        varAcumuladorA = 0;
        
        //Calcular la tabla 1
        for (int i = 0; i < 8; i++){
           varCadena1 = modelo1.getValueAt(i, 1).toString();
           varCadena2 = modelo1.getValueAt(i, 2).toString();
           if ( (!varCadena1.matches("[0-9.]+")) || (!varCadena2.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Integer.parseInt(modelo1.getValueAt(i, 1).toString());
            varPrecioA = Double.parseDouble(modelo1.getValueAt(i, 2).toString());
            varTotalA = varCantidadA * varPrecioA;
            varAcumuladorA = varAcumuladorA + varTotalA;
            modelo1.setValueAt(varTotalA, i, 3);
           }
        }
        jLabel4.setText("$ " + varAcumuladorA);
        jLabel5.setText("$ " + varAcumuladorA);
        
        varTotalInversion = varAcumuladorA + varAcumuladorB + varAcumuladorC + varAcumuladorD + varAcumuladorE +
                varAcumuladorF + varAcumuladorG;
        
        jLabel31.setText("$ " + varTotalInversion);
    }//GEN-LAST:event_jTable1MouseEntered

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TABLA 02
        DefaultTableModel modelo2 = (DefaultTableModel) jTable2.getModel();
        int varCantidadA = 0;
        double varPrecioA = 0, varTotalA = 0;
        String varCadena1, varCadena2;
        
        varAcumuladorB = 0;
        
        //Calcular la tabla 1
        for (int i = 0; i < 8; i++){
           varCadena1 = modelo2.getValueAt(i, 1).toString();
           varCadena2 = modelo2.getValueAt(i, 2).toString();
           if ( (!varCadena1.matches("[0-9.]+")) || (!varCadena2.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Integer.parseInt(modelo2.getValueAt(i, 1).toString());
            varPrecioA = Double.parseDouble(modelo2.getValueAt(i, 2).toString());
            varTotalA = varCantidadA * varPrecioA;
            varAcumuladorB = varAcumuladorB + varTotalA;
            modelo2.setValueAt(varTotalA, i, 3);
           }
        }
        jLabel8.setText("$ " + varAcumuladorB);
        jLabel9.setText("$ " + varAcumuladorB);
        
        varTotalInversion = varAcumuladorA + varAcumuladorB + varAcumuladorC + varAcumuladorD + varAcumuladorE +
                varAcumuladorF + varAcumuladorG;
        
        jLabel31.setText("$ " + varTotalInversion);
    }//GEN-LAST:event_jTable2MouseEntered

    private void jTable3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseEntered
        // TABLA 03
        DefaultTableModel modelo3 = (DefaultTableModel) jTable3.getModel();
        int varCantidadA = 0;
        double varPrecioA = 0, varTotalA = 0;
        String varCadena1, varCadena2;
        
        varAcumuladorC = 0;
        
        //Calcular la tabla 1
        for (int i = 0; i < 8; i++){
           varCadena1 = modelo3.getValueAt(i, 1).toString();
           varCadena2 = modelo3.getValueAt(i, 2).toString();
           if ( (!varCadena1.matches("[0-9.]+")) || (!varCadena2.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Integer.parseInt(modelo3.getValueAt(i, 1).toString());
            varPrecioA = Double.parseDouble(modelo3.getValueAt(i, 2).toString());
            varTotalA = varCantidadA * varPrecioA;
            varAcumuladorC = varAcumuladorC + varTotalA;
            modelo3.setValueAt(varTotalA, i, 3);
           }
        }
        jLabel12.setText("$ " + varAcumuladorC);
        jLabel13.setText("$ " + varAcumuladorC);
        
        varTotalInversion = varAcumuladorA + varAcumuladorB + varAcumuladorC + varAcumuladorD + varAcumuladorE +
                varAcumuladorF + varAcumuladorG;
        
        jLabel31.setText("$ " + varTotalInversion);
    }//GEN-LAST:event_jTable3MouseEntered

    private void jTable4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseEntered
        // TABLA 04
        DefaultTableModel modelo4 = (DefaultTableModel) jTable4.getModel();
        int varCantidadA = 0;
        double varPrecioA = 0, varTotalA = 0;
        String varCadena1, varCadena2;
        
        varAcumuladorD = 0;
        
        //Calcular la tabla 1
        for (int i = 0; i < 8; i++){
           varCadena1 = modelo4.getValueAt(i, 1).toString();
           varCadena2 = modelo4.getValueAt(i, 2).toString();
           if ( (!varCadena1.matches("[0-9.]+")) || (!varCadena2.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Integer.parseInt(modelo4.getValueAt(i, 1).toString());
            varPrecioA = Double.parseDouble(modelo4.getValueAt(i, 2).toString());
            varTotalA = varCantidadA * varPrecioA;
            varAcumuladorD = varAcumuladorD + varTotalA;
            modelo4.setValueAt(varTotalA, i, 3);
           }
        }
        jLabel16.setText("$ " + varAcumuladorD);
        jLabel17.setText("$ " + varAcumuladorD);
        
        varTotalInversion = varAcumuladorA + varAcumuladorB + varAcumuladorC + varAcumuladorD + varAcumuladorE +
                varAcumuladorF + varAcumuladorG;
        
        jLabel31.setText("$ " + varTotalInversion);
    }//GEN-LAST:event_jTable4MouseEntered

    private void jTable5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseEntered
        // TABLA 05
        DefaultTableModel modelo5 = (DefaultTableModel) jTable5.getModel();
        int varCantidadA = 0;
        double varPrecioA = 0, varTotalA = 0;
        String varCadena1, varCadena2;
        
        varAcumuladorE = 0;
        
        //Calcular la tabla 1
        for (int i = 0; i < 8; i++){
           varCadena1 = modelo5.getValueAt(i, 1).toString();
           varCadena2 = modelo5.getValueAt(i, 2).toString();
           if ( (!varCadena1.matches("[0-9.]+")) || (!varCadena2.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Integer.parseInt(modelo5.getValueAt(i, 1).toString());
            varPrecioA = Double.parseDouble(modelo5.getValueAt(i, 2).toString());
            varTotalA = varCantidadA * varPrecioA;
            varAcumuladorE = varAcumuladorE + varTotalA;
            modelo5.setValueAt(varTotalA, i, 3);
           }
        }
        jLabel20.setText("$ " + varAcumuladorE);
        jLabel21.setText("$ " + varAcumuladorE);
        
        varTotalInversion = varAcumuladorA + varAcumuladorB + varAcumuladorC + varAcumuladorD + varAcumuladorE +
                varAcumuladorF + varAcumuladorG;
        
        jLabel31.setText("$ " + varTotalInversion);
    }//GEN-LAST:event_jTable5MouseEntered

    private void jTable6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6MouseEntered
        // TABLA 06
        DefaultTableModel modelo6 = (DefaultTableModel) jTable6.getModel();
        int varCantidadA = 0;
        double varPrecioA = 0, varTotalA = 0;
        String varCadena1, varCadena2;
        
        varAcumuladorF = 0;
        
        for (int i = 0; i < 3; i++){
           varCadena1 = modelo6.getValueAt(i, 1).toString();
           varCadena2 = modelo6.getValueAt(i, 2).toString();
           if ( (!varCadena1.matches("[0-9.]+")) || (!varCadena2.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Integer.parseInt(modelo6.getValueAt(i, 1).toString());
            varPrecioA = Double.parseDouble(modelo6.getValueAt(i, 2).toString());
            varTotalA = varCantidadA * varPrecioA;
            varAcumuladorF = varAcumuladorF + varTotalA;
            modelo6.setValueAt(varTotalA, i, 3);
           }
        }
        jLabel24.setText("$ " + varAcumuladorF);
        jLabel25.setText("$ " + varAcumuladorF);
        
        varTotalInversion = varAcumuladorA + varAcumuladorB + varAcumuladorC + varAcumuladorD + varAcumuladorE +
                varAcumuladorF + varAcumuladorG;
        
        jLabel31.setText("$ " + varTotalInversion);
    }//GEN-LAST:event_jTable6MouseEntered

    private void jTable7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable7MouseEntered
        // TABLA 07
        DefaultTableModel modelo7 = (DefaultTableModel) jTable7.getModel();
        int varCantidadA = 0;
        double varPrecioA = 0, varTotalA = 0;
        String varCadena1, varCadena2;
        
        varAcumuladorG = 0;
        
        for (int i = 0; i < 3; i++){
           varCadena1 = modelo7.getValueAt(i, 1).toString();
           varCadena2 = modelo7.getValueAt(i, 2).toString();
           if ( (!varCadena1.matches("[0-9.]+")) || (!varCadena2.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Integer.parseInt(modelo7.getValueAt(i, 1).toString());
            varPrecioA = Double.parseDouble(modelo7.getValueAt(i, 2).toString());
            varTotalA = varCantidadA * varPrecioA;
            varAcumuladorG = varAcumuladorG + varTotalA;
            modelo7.setValueAt(varTotalA, i, 3);
           }
        }
        jLabel28.setText("$ " + varAcumuladorG);
        jLabel29.setText("$ " + varAcumuladorG);
        
        varTotalInversion = varAcumuladorA + varAcumuladorB + varAcumuladorC + varAcumuladorD + varAcumuladorE +
                varAcumuladorF + varAcumuladorG;
        
        jLabel31.setText("$ " + varTotalInversion);
    }//GEN-LAST:event_jTable7MouseEntered

    private void jTable8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable8MouseEntered
        // TABLA 08
        DefaultTableModel modelo8 = (DefaultTableModel) jTable8.getModel();
        double varCantidadA = 0;
        double varTotalA = 0, varPorcentaje = 0, varAcumuladorPorcentaje = 0;
        String varCadena1;
        
        for (int i = 0; i < 2; i++){
           varCadena1 = modelo8.getValueAt(i, 1).toString();
           if ( (!varCadena1.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Double.parseDouble(modelo8.getValueAt(i, 1).toString());
            varTotalA = varTotalA + varCantidadA;
           }
        }
        modelo8.setValueAt(varTotalA, 2, 1);
        
        if (varTotalA > 0){
            for (int i = 0; i < 2; i++){
                varCadena1 = modelo8.getValueAt(i, 1).toString();
                if ( (!varCadena1.matches("[0-9.]+")) ){
                    JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
                }
                else{
                    varCantidadA = Double.parseDouble(modelo8.getValueAt(i, 1).toString());
                    varPorcentaje = (varCantidadA / varTotalA) * 100;
                    //Hace falta truncarlo
                    modelo8.setValueAt(varPorcentaje + "%", i, 2);
                    varAcumuladorPorcentaje = varAcumuladorPorcentaje + varPorcentaje;
                }
            }
            modelo8.setValueAt(varAcumuladorPorcentaje + "%", 2, 2);
        }
    }//GEN-LAST:event_jTable8MouseEntered

    private void jTable9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable9MouseEntered
        // TABLA 09
        DefaultTableModel modelo8 = (DefaultTableModel) jTable8.getModel();
        DefaultTableModel modelo9 = (DefaultTableModel) jTable9.getModel();
        double varCantidadA = 0;
        double varTotalA = 0, varCantidadB = 0, varAcumuladorCantidad = 0;
        String varCadena1;
        
        for (int i = 0; i < 3; i++){
           varCadena1 = modelo9.getValueAt(i, 1).toString();
           if ( (!varCadena1.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Double.parseDouble(modelo9.getValueAt(i, 1).toString());
            varTotalA = varTotalA + varCantidadA;
           }
        }
        
        modelo9.setValueAt(varTotalA + "%", 3, 1);
        
        varCadena1 = modelo8.getValueAt(1, 1).toString();
        if ( (!varCadena1.matches("[0-9.]+")) ){
            JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
        }
        else{
            varCantidadB = Double.parseDouble(varCadena1);
            if (varTotalA > 0){
                for (int i = 0; i < 3; i++){
                    varCadena1 = modelo9.getValueAt(i, 1).toString();
                    if ( (!varCadena1.matches("[0-9.]+")) ){
                        JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
                    }
                    else{
                        varCantidadA = Double.parseDouble(modelo9.getValueAt(i, 1).toString());
                        varCantidadA = (varCantidadB * varCantidadA) / 100;
                        modelo9.setValueAt(varCantidadA, i, 2);
                        varAcumuladorCantidad = varAcumuladorCantidad + varCantidadA;
                    }
                }
                //Verificar que coinciden los totales
                modelo9.setValueAt(varAcumuladorCantidad, 3, 2);
            }
        }
    }//GEN-LAST:event_jTable9MouseEntered

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        //Llenar tabla 11
        DefaultTableModel modelo11 = (DefaultTableModel) jTable11.getModel();
        DefaultTableModel modelo12 = (DefaultTableModel) jTable12.getModel();
        modelo11.setValueAt("MAQUINARIA Y EQUIPO", 0, 0);
        modelo11.setValueAt(varAcumuladorA, 0, 1);
        modelo11.setValueAt("EQUIPO DE CÓMPUTO", 1, 0);
        modelo11.setValueAt(varAcumuladorC, 1, 1);
        modelo11.setValueAt("EQUIPO DE OFICINA", 2, 0);
        modelo11.setValueAt(varAcumuladorD, 2, 1);
        modelo11.setValueAt("EQUIPO DE TRANSPORTE", 3, 0);
        modelo11.setValueAt(varAcumuladorB, 3, 1);
        modelo11.setValueAt("CONSTRUCCIONES", 4, 0);
        modelo11.setValueAt(varAcumuladorE, 4, 1);
        
        //Llenar tabla 12
        modelo12.setValueAt("X", 0, 0);
        modelo12.setValueAt(varAcumuladorG, 0, 1);
        
        //Llenar la tabla 13
        DefaultTableModel modelo8 = (DefaultTableModel) jTable8.getModel();
        DefaultTableModel modelo13 = (DefaultTableModel) jTable13.getModel();
        double varCantidadA = 0;
        double varTotalA = 0, varCantidadB = 0, varAcumuladorCantidad = 0;
        String varCadena1;
        
        for (int i = 0; i < 1; i++){
           varCadena1 = modelo8.getValueAt(i, 1).toString();
           if ( (!varCadena1.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Double.parseDouble(modelo8.getValueAt(i, 1).toString());
            modelo13.setValueAt("FINANCIAMIENTO EXTERNO", 0, 0);
            modelo13.setValueAt(varCantidadA, 0, 1);
            jLabel49.setText("$ " + varCantidadA);
           }
        }
        
        //Llenar tabla 14
        DefaultTableModel modelo14 = (DefaultTableModel) jTable14.getModel();
        
        for (int i = 1; i < 2; i++){
           varCadena1 = modelo8.getValueAt(i, 1).toString();
           if ( (!varCadena1.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Double.parseDouble(modelo8.getValueAt(i, 1).toString());
            modelo14.setValueAt("APORTACIONES DE SOCIOS", 0, 0);
            modelo14.setValueAt(varCantidadA, 0, 1);
            jLabel52.setText("$ " + varCantidadA);
           }
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTable10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable10MouseEntered
        // TABLA 10
        DefaultTableModel modelo10 = (DefaultTableModel) jTable10.getModel();
        double varCantidadA = 0;
        double varTotalA = 0, varCantidadB = 0, varAcumuladorCantidad = 0;
        String varCadena1;
        
        for (int i = 0; i < 2; i++){
           varCadena1 = modelo10.getValueAt(i, 1).toString();
           if ( (!varCadena1.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Double.parseDouble(modelo10.getValueAt(i, 1).toString());
            varTotalA = varTotalA + varCantidadA;
           }
        }
        jLabel38.setText("$ " + varTotalA);
        varAcumuladorActivoCorriente = varTotalA;
        varTotalActivo = varAcumuladorActivoCorriente + varAcumuladorActivoFijo +
                varAcumuladorActivoDiferido;
        jLabel46.setText("$ " + varTotalActivo);
    }//GEN-LAST:event_jTable10MouseEntered

    private void jTable11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable11MouseEntered
        // TABLA 11
        DefaultTableModel modelo11 = (DefaultTableModel) jTable11.getModel();
        double varCantidadA = 0;
        double varTotalA = 0, varCantidadB = 0, varAcumuladorCantidad = 0;
        String varCadena1;
        
        for (int i = 0; i < 5; i++){
           varCadena1 = modelo11.getValueAt(i, 1).toString();
           if ( (!varCadena1.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Double.parseDouble(modelo11.getValueAt(i, 1).toString());
            varTotalA = varTotalA + varCantidadA;
           }
        }
        jLabel41.setText("$ " + varTotalA);
        varAcumuladorActivoFijo = varTotalA;
        varTotalActivo = varAcumuladorActivoCorriente + varAcumuladorActivoFijo +
                varAcumuladorActivoDiferido;
        jLabel46.setText("$ " + varTotalActivo);
    }//GEN-LAST:event_jTable11MouseEntered

    private void jTable12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable12MouseEntered
        // TABLA 12
        DefaultTableModel modelo12 = (DefaultTableModel) jTable12.getModel();
        double varCantidadA = 0;
        double varTotalA = 0, varCantidadB = 0, varAcumuladorCantidad = 0;
        String varCadena1;
        
        for (int i = 0; i < 1; i++){
           varCadena1 = modelo12.getValueAt(i, 1).toString();
           if ( (!varCadena1.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Double.parseDouble(modelo12.getValueAt(i, 1).toString());
            varTotalA = varTotalA + varCantidadA;
           }
        }
        jLabel44.setText("$ " + varTotalA);
        varAcumuladorActivoDiferido = varTotalA;
        varTotalActivo = varAcumuladorActivoCorriente + varAcumuladorActivoFijo +
                varAcumuladorActivoDiferido;
        jLabel46.setText("$ " + varTotalActivo);
    }//GEN-LAST:event_jTable12MouseEntered

    private void jTable13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable13MouseEntered
        // TABLA 13
        DefaultTableModel modelo13 = (DefaultTableModel) jTable13.getModel();
        double varCantidadA = 0;
        double varTotalA = 0, varCantidadB = 0, varAcumuladorCantidad = 0;
        String varCadena1;
        
        varAcumuladorPasivoCirculante = 0;
        
        for (int i = 0; i < 1; i++){
           varCadena1 = modelo13.getValueAt(i, 1).toString();
           if ( (!varCadena1.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Double.parseDouble(modelo13.getValueAt(i, 1).toString());
            varTotalA = varTotalA + varCantidadA;
           }
        }
        varAcumuladorPasivoCirculante = varAcumuladorPasivoCirculante + varTotalA;
        varPasivoMasCapital = varAcumuladorPasivoCirculante + varAcumuladorCapital;
        jLabel54.setText("$ " + varPasivoMasCapital);
    }//GEN-LAST:event_jTable13MouseEntered

    private void jTable14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable14MouseEntered
        // TODO add your handling code here:
        // TABLA 14
        DefaultTableModel modelo14 = (DefaultTableModel) jTable14.getModel();
        double varCantidadA = 0;
        double varTotalA = 0, varCantidadB = 0, varAcumuladorCantidad = 0;
        String varCadena1;
        
        varAcumuladorCapital = 0;
        
        for (int i = 0; i < 1; i++){
           varCadena1 = modelo14.getValueAt(i, 1).toString();
           if ( (!varCadena1.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Double.parseDouble(modelo14.getValueAt(i, 1).toString());
            varTotalA = varTotalA + varCantidadA;
           }
        }
        varAcumuladorCapital = varAcumuladorCapital + varTotalA;
        varPasivoMasCapital = varAcumuladorPasivoCirculante + varAcumuladorCapital;
        jLabel54.setText("$ " + varPasivoMasCapital);
    }//GEN-LAST:event_jTable14MouseEntered

    private void jTable15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable15MouseEntered
        // TABLA 15
    
        DefaultTableModel modelo15 = (DefaultTableModel) jTable15.getModel();
         int varCantidadA = 0;
        double varPrecioA = 0, varTotalA = 0;
        String varCadena1, varCadena2;
        
        varAcumuladorMPrimaDirecta = 0;
        
        //Calcular la tabla 1
        for (int i = 0; i < 6; i++){
           varCadena1 = modelo15.getValueAt(i, 1).toString();
           varCadena2 = modelo15.getValueAt(i, 2).toString();
           if ( (!varCadena1.matches("[0-9.]+")) || (!varCadena2.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Integer.parseInt(modelo15.getValueAt(i, 1).toString());
            varPrecioA = Double.parseDouble(modelo15.getValueAt(i, 2).toString());
            varTotalA = varCantidadA * varPrecioA;
            varAcumuladorMPrimaDirecta = varAcumuladorMPrimaDirecta + varTotalA;
            modelo15.setValueAt(varTotalA, i, 4);
           }
        }
        modelo15.setValueAt("Totales", 6, 0);
        modelo15.setValueAt(varAcumuladorMPrimaDirecta, 6, 4);
    
    }//GEN-LAST:event_jTable15MouseEntered

    private void jTable16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable16MouseEntered
        // TABLA 16
        DefaultTableModel modelo16 = (DefaultTableModel) jTable16.getModel();
         int varCantidadA = 0;
        double varPrecioA = 0, varTotalA = 0;
        String varCadena1, varCadena2;
        
        varAcumuladorMPrimaIndirecta = 0;
        
        //Calcular la tabla 1
        for (int i = 0; i < 6; i++){
           varCadena1 = modelo16.getValueAt(i, 1).toString();
           varCadena2 = modelo16.getValueAt(i, 2).toString();
           if ( (!varCadena1.matches("[0-9.]+")) || (!varCadena2.matches("[0-9.]+")) ){
               JOptionPane.showMessageDialog(null, "Error: existe un caracter no numérico.");
           }
           else{
            varCantidadA = Integer.parseInt(modelo16.getValueAt(i, 1).toString());
            varPrecioA = Double.parseDouble(modelo16.getValueAt(i, 2).toString());
            varTotalA = varCantidadA * varPrecioA;
            varAcumuladorMPrimaIndirecta = varAcumuladorMPrimaIndirecta + varTotalA;
            modelo16.setValueAt(varTotalA, i, 4);
           }
        }
        modelo16.setValueAt("Totales", 6, 0);
        modelo16.setValueAt(varAcumuladorMPrimaIndirecta, 6, 4);

    }//GEN-LAST:event_jTable16MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCostos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable13;
    private javax.swing.JTable jTable14;
    private javax.swing.JTable jTable15;
    private javax.swing.JTable jTable16;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    // End of variables declaration//GEN-END:variables
}
